name: Cypress Magento Auto Tests

on: 
  push:
    branches:
      - master   # Run tests when pushing to the main branch
  pull_request:
    branches:
      - master   # Run tests on pull requests targeting the main branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest   # Use the latest Ubuntu environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4    # Check out your repository code

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'         # Specify the Node.js version

      - name: Install dependencies
        run: npm install             # Install project dependencies

      - name: Run Cypress tests
        run: npx cypress run         # Run Cypress tests

      - name: Upload test artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots  # Upload screenshots for failed tests
